# Utiliser une image de base légère Node.js
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le reste des fichiers de l'application
COPY . .
RUN npm install typescript -g  # Ensure typescript is installed globally
RUN npx tsc

# Créer le dossier uploads
RUN mkdir -p uploads

# Compiler le code TypeScript
RUN npx tsc

# Exposer le port sur lequel l'application va tourner
EXPOSE 3003

# Démarrer l'application
CMD ["node", "dist/index.js"]
